// libs/design-system/src/components/ui/Container/Container.tsx
import React from "react";

import { cn } from "@/lib/utils";

export type ContainerProps = React.HTMLAttributes<HTMLDivElement>;

export const Container = React.forwardRef<HTMLDivElement, ContainerProps>(
  ({ className, ...props }: ContainerProps) => {
    return (
      <div
        className={cn("zd-px-8 lg:zd-max-w-[1024px] lg:zd-m-auto", className)}
        {...props}
      />
    );
  },
);

// apps/sveltastic/src/lib/components/ui/Container/container.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { SvelteHTMLElements } from "svelte/elements";

  type $$Props = SvelteHTMLElements["div"];
  let className: $$Props["class"] = undefined;
  export { className as class };
</script>

<div
  class={cn("zd-px-8 lg:zd-max-w-[1024px] lg:zd-m-auto", className)}
  {...$$restProps}
>
  <slot />
</div>
